- name: systemd-resolved | config
  tags:
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  notify: restart resolved

- name: systemd-resolved | service
  systemd:
    name: systemd-resolved
    masked: no
    enabled: yes
    state: started
  notify: use resolved

- name: systemd-resolved | stub /etc/resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
