- name: systemd-resolved | config
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  notify: restart resolved

- name: systemd-resolved | stop to use unbound
  systemd:
    name: systemd-resolved
    enabled: false
    state: stopped
  notify: stop resolved
