- name: systemd-resolved | config
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  notify: restart resolved

- name: systemd-resolved | stop for using unbound
  systemd:
    name: systemd-resolved
    enabled: false
    state: stopped
  notify: stop resolved
  
- name: Delete old resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  
- name: Create new resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    
- name: Delete etc/hosts
  ansible.builtin.file:
    path: /etc/hosts
    state: absent
  
- name: Create etc/hosts with hostname 
  template:
    src: hosts.j2
    dest: /etc/hosts
  
