      - name: Set prompt for LTS upgrades
        ansible.builtin.lineinfile:
          path: /etc/update-manager/release-upgrades
          regexp: '^Prompt='
          line: 'Prompt=normal' # or 'Prompt=lts'
          
      - name: Upgrade all packages to the latest version
        apt: update_cache=yes upgrade=full

      - name: Ensure update-manager-core is installed.
        apt: name=update-manager-core state=present

      - name: Run do-release-upgrade non-interactively.
        command: do-release-upgrade -f DistUpgradeViewNonInteractive

      - name: Reboot the server.
        ansible.builtin.reboot:
          reboot_timeout: 120
