- name: Change SSH port
  shell:
    cmd: grep -r Port /etc/ssh -l | xargs -n 1 sed -i -e "/Port /c\Port {{ SSH_PORT }}"
- name: Restart ssh
  service:
    name: ssh
    state: restarted
    daemon_reload: true
