- name: Add user
  ansible.builtin.user:
    name: "{{ user_to_create }}"
    shell: /bin/bash
    groups: sudo,docker
    password: "{{ user_password | password_hash('sha512') }}"
    append: yes
    update_password: on_create
  register: "xray_user"
- name: Make sudo with nopasswd
  community.general.sudoers:
    name: make_sudo_nopasswd
    user: "{{ user_to_create }}"
    state: present
    commands: ALL
- name: Add ssh_pbk to user
  ansible.posix.authorized_key:
    user: "{{ user_to_create }}"
    state: "present"
    key: "{{ ssh_public_key }}"
