---
# handlers file for vps-setup
- name: Restart xray
  service:
    name: xray
    state: restarted
- name: Restart caddy 
  service:
    name: caddy
    state: restarted
- name: Restart ssh 
  service:
    name: ssh
    state: restarted
    daemon_reload: true
- name: Restart marzban 
  service:
    name: marzban
    state: restarted
- name: use resolved
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
- name: restart resolved
  service:
    name: systemd-resolved
    state: restarted
